#!/usr/bin/env python3
"""Higher moments of the node voltages: is the process Gaussian, and where?

Everything else in this write-up is a second moment. `Sigma = c G^-1` fixes those and
says nothing about the rest of the distribution, so the third and fourth moments are a
free check on it - and the answer is what decides whether "Ornstein-Uhlenbeck" is a fair
description of the board or just a convenient one.

Two things are computed, both from the same gnd2 captures as the headline result.

IN BAND, per record, band-limited 200 Hz - 50 kHz with make_figures.bandpass (the same
band-limiter every published figure uses - do not substitute another, the estimators do
not agree to better than a percent):

    skewness and excess kurtosis on each node, and the two fourth-moment identities that
    a jointly Gaussian pair satisfies exactly (Isserlis / Wick),

        <x1^2 x2^2> = <x1^2><x2^2> + 2<x1 x2>^2        <x1^3 x2> = 3<x1^2><x1 x2>

    quoted as the relative residual of each, mean +- SEM over the 30 records. These two
    are the useful ones: a single channel can be made Gaussian by a linear filter, but
    they constrain the JOINT distribution, which is what the covariance claim is about.

ACROSS THE BAND EDGE, on the unfiltered record, sliced the same way into < 200 Hz,
200 Hz - 50 kHz and > 50 kHz: excess kurtosis and the share of total power in each.
This is why the band limit is not an analysis convenience - most of the raw record's
power sits above 50 kHz and is strongly non-Gaussian, and that part is the oscilloscope
(README, Measurement traps: the min/max envelope and the >500 kHz folding), not the board.

    python3 moments.py                 # writes data/moments.csv, prints the table
    RAW=/path/to/captures python3 moments.py
"""
import os
import sys

import numpy as np

import make_figures as M

BANDS = [("0-200", 0.0, 200.0),
         ("200-50k", 200.0, 50e3),
         ("50k-up", 50e3, np.inf)]


def sem(v):
    """Standard error of the mean over records."""
    return float(np.std(v, ddof=1) / np.sqrt(len(v)))


def in_band():
    """Skewness, excess kurtosis and the two Isserlis residuals, per record."""
    skew, kurt, iss22, iss31 = [[], []], [[], []], [], []
    for nm in M.FINAL:
        dt, x, y = M.load(nm)
        x = M.bandpass(x, dt, *M.BAND)
        y = M.bandpass(y, dt, *M.BAND)
        for i, v in enumerate((x, y)):
            s = v.std()
            skew[i].append(float((v ** 3).mean() / s ** 3))
            kurt[i].append(float((v ** 4).mean() / s ** 4 - 3.0))
        vx, vy, cxy = (x * x).mean(), (y * y).mean(), (x * y).mean()
        iss22.append(float((x * x * y * y).mean() / (vx * vy + 2 * cxy ** 2) - 1.0))
        iss31.append(float((x ** 3 * y).mean() / (3 * vx * cxy) - 1.0))
    return skew, kurt, iss22, iss31


def across_the_edge():
    """Excess kurtosis and power share in each of the three slices, per record."""
    kurt = {b: [[], []] for b, _, _ in BANDS}
    share = {b: [[], []] for b, _, _ in BANDS}
    for nm in M.FINAL:
        dt, x, y = M.load(nm)
        for i, v in enumerate((x, y)):
            total = ((v - v.mean()) ** 2).mean()
            for name, lo, hi in BANDS:
                s = M.bandpass(v, dt, lo, hi)
                p = (s ** 2).mean()
                kurt[name][i].append(float((s ** 4).mean() / p ** 2 - 3.0))
                share[name][i].append(float(p / total))
    return kurt, share


def main():
    skew, kurt, iss22, iss31 = in_band()
    ek, share = across_the_edge()

    rows = []
    for i in (0, 1):
        rows.append(("200-50k", "skewness", i + 1, np.mean(skew[i]), sem(skew[i])))
        rows.append(("200-50k", "excess_kurtosis", i + 1, np.mean(kurt[i]), sem(kurt[i])))
    rows.append(("200-50k", "isserlis_x1sq_x2sq", 0, np.mean(iss22), sem(iss22)))
    rows.append(("200-50k", "isserlis_x1cu_x2", 0, np.mean(iss31), sem(iss31)))
    for name, _, _ in BANDS:
        for i in (0, 1):
            rows.append((name, "excess_kurtosis_unfiltered", i + 1,
                         np.mean(ek[name][i]), sem(ek[name][i])))
            rows.append((name, "power_share_unfiltered", i + 1,
                         np.mean(share[name][i]), sem(share[name][i])))

    M.write_csv(
        "moments.csv", "band,quantity,node,value,std_err",
        [(b, q, n, f"{v:+.5f}", f"{e:.5f}") for b, q, n, v, e in rows],
        "Third and fourth moments of the node voltages, 30 gnd2 records, mean +- SEM "
        "over records. The 200-50k rows are band-limited with make_figures.bandpass; the "
        "*_unfiltered rows slice the RAW record the same way, to show what the band limit "
        "removes. isserlis_* are the relative residuals of the two fourth-moment "
        "identities a jointly Gaussian pair satisfies exactly; node 0 means both. "
        "Generated by moments.py.")

    print("\n  in band, 200 Hz - 50 kHz")
    for i in (0, 1):
        print(f"    node {i+1}  skew {np.mean(skew[i]):+.4f} +- {sem(skew[i]):.4f}"
              f"   excess kurtosis {np.mean(kurt[i]):+.4f} +- {sem(kurt[i]):.4f}")
    print(f"    Isserlis <x1^2 x2^2> {np.mean(iss22):+.4f} +- {sem(iss22):.4f}"
          f"   <x1^3 x2> {np.mean(iss31):+.4f} +- {sem(iss31):.4f}")
    print("\n  unfiltered record, sliced")
    for name, _, _ in BANDS:
        print(f"    {name:>8}  excess kurtosis "
              f"{np.mean(ek[name][0]):+.3f} / {np.mean(ek[name][1]):+.3f}"
              f"   power share {100*np.mean(share[name][0]):5.1f} % / "
              f"{100*np.mean(share[name][1]):5.1f} %")


if __name__ == "__main__":
    sys.exit(main())
